[package]
name = "sitewriter"
version = "0.4.0"
authors = ["Edgar <git@edgarluque.com>"]
edition = "2018"
description = "A sitemap writing library."
readme = "README.md"
documentation = "https://docs.rs/sitewriter"
repository = "https://github.com/edg-l/sitewriter"
license = "MIT"
keywords = ["sitemap", "sitemapindex", "xml", "parser"]
categories = ["parsing"]

[dependencies]
chrono = "0.4.19"
derive_builder = "0.10.0"
quick-xml = "0.22.0"
url = "2.2.1"

[dev-dependencies]
criterion = { version = "0.3.4", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false
