[package]
name = "sitewriter"
version = "0.3.0"
authors = ["Edgar <git@edgarluque.com>"]
edition = "2018"
description = "A sitemap writing library."
readme = "README.md"
documentation = "https://docs.rs/sitewriter"
repository = "https://github.com/edg-l/sitewriter"
license = "MIT"
keywords = ["sitemap", "sitemapindex", "xml", "parser"]
categories = ["parsing"]

[dependencies]
chrono = "0.4"
quick-xml = "0.20"
